development:
  adapter: postgresql
  database: quicksprout_development
  host: localhost
  
test:
  adapter: postgresql
  database: quicksprout_test
  host: localhost
  
production:
  adapter: postgresql
  database: quicksprout_production
  host: localhost
