development:
  adapter: postgresql
  database: repo_deployer_development
  host: localhost
  
test:
  adapter: postgresql
  database: repo_deployer_test
  host: localhost
  
production:
  adapter: postgresql
  database: repo_deployer_production
  host: localhost
